---
title: "GME Control Chart"
author: "JiggsNibbly"
date: "2022-08-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(zoo)
library(qicharts)
library(lubridate)
```

## Read in data and create base data set

Stock data is extracted from WRDS in .dta, and a daily percent change in closing price is
calculated and graphed over time.

```{r code}
df <- read_dta("../data/GME_Prices.dta")
vtable::vtable(df)
df <- df %>%
  arrange(datadate) %>%
  mutate(prccd_delta = (prccd/lag(prccd)-1)*100) %>%
  mutate(week = floor_date(datadate, "weeks", week_start=1))
  

ggplot(data=df, aes(x=datadate,y=prccd_delta)) +
  geom_point() + geom_line()
```

## Creating the control chart statistics

A number of statistics need to be calculated for the control chart.

```{r code}
xbarbar <- mean(df$prccd_delta)
n <- 5
d_2 <- 2.326
d_3 <- 0
d_4 <- 2.114

df <- df %>%
  mutate(xbar = rollmeanr(prccd_delta,k=5,fill=NA))

qic(
  y=prccd_delta,
    x=week,
    data=df,
    chart='xbar',
    main='Percent Change (Xbar chart)',
    ylab='Percent Change',
    xlab='Date'
    )

qic(
  y=prccd_delta,
  x=week,
  data=df,
  chart='s',
  main='Standard deviation of percent change (S chart)',
  ylab='Percent change',
  xlab='Date'
)
```

